### ISSUE TITLE
TTS API 요청 시 RestClientException 발생

### ISSUE THREAD

**Issue by ja7811** [umc-owncast/OwnCast_backend#66]
```
org.springframework.web.client.RestClientException: Error while extracting response for type [interface java.util.Map] and content type [application/json;charset=UTF-8]
	at ...생략...
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:672) ~[spring-web-6.1.10.jar:6.1.10]
	at com.umc.owncast.domain.cast.service.TTSService.requestSpeech(TTSService.java:66) ~[classes/:na]
	at com.umc.owncast.domain.cast.service.TTSService.createSpeech(TTSService.java:28) ~[classes/:na]
	at com.umc.owncast.domain.cast.service.CastServiceImpl.handleCastCreation(CastServiceImpl.java:62) ~[classes/:na]
	at com.umc.owncast.domain.cast.service.CastServiceImpl.createCastByKeyword(CastServiceImpl.java:47) ~[classes/:na]
	at com.umc.owncast.domain.cast.controller.CastController.createCastByKeyword(CastController.java:35) ~[classes/:na]
       ... 생략
```
캐스트 생성 API 호출 시 `TTSService`에서 무한로딩 걸리더니 이 에러를 뿜고 멈추네요
이쪽 코드는 최근에 건드린 적 없는 걸로 알아서 갑자기 왜 에러났는지는 아직 모르겠지만
함 찾아보고 고치면 PR 날릴게요

**Comment by ja7811** [comment]
또 다시 확인해보니까 안나네요;; 🧐

혹시나 해서 일단 이슈는 열어두고
앞으로도 안나면 닫을게요
